### ISSUE TITLE
composer.json should require phpunit/phpunit ~3.7

### ISSUE THREAD

**Issue by kwisatz** [Behat/CommonContexts#51]
In _WebApiContext.php_, you're requiring _PHPUnit/Autoload.php_. However, since version 4.0 of phpunit, it is no longer bringing its own Autoloader but using composer as well.

Please add a require dependency on **~3.7** or alternatively please release a new tag of behat/common-contexts that can deal with phpunit 4.0

**Comment by MacDada** [comment]
Hi, I've upgraded phpunit `~3.7` to `~3.8` and behat freaked out:

`PHP Warning:  require_once(PHPUnit/Autoload.php): failed to open stream: No such file or directory in /vagrant/vendor/behat/common-contexts/Behat/CommonContexts/WebApiContext.php on line 11`

In composer I requrie "any" version `"behat/common-contexts": "*",` but I also `"prefer-stable": true,` which in the end gives me version `v.1.2.0`.

I see that the fix is merged to `master` now, but why is there no release for more than a year?
